include:
  - project: perun/common
    file: /templates/.gitlab-ci-template.yml

variables:
  # release from production branch instead of main
  RELEASE_FROM_PRODUCTION: 1

maven-build:
  image: $CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX/maven:3-openjdk-17
  stage: build
  script:
    - mvn -B -Dmaven.repo.local=.m2/repository clean install
  rules:
    - if: "$CI_PIPELINE_SOURCE != 'schedule'"
