include:
  - project: perun/common
    file: /templates/.gitlab-ci-template.yml

# run on production branch instead of main
semantic-release:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "production" && $CI_PIPELINE_SOURCE != "schedule"'

maven-build:
  image: $CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX/maven:3-openjdk-17
  stage: build
  script:
    - mvn -B -Dmaven.repo.local=.m2/repository clean install
  rules:
    - if: "$CI_PIPELINE_SOURCE != 'schedule'"
